version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_APPLICATION_NAME=challenge
      - SPRING_DATASOURCE_DRIVERCLASSNAME=org.h2.Driver
      - SPRING_DATASOURCE_URL=jdbc:h2:mem:w2m-challenge;
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_DATABASE-PLATFORM=org.hibernate.dialect.H2Dialect
      - SPRING_JPA_HIBERNATE_DDL-AUTO=update
      - SPRING_H2_CONSOLE_ENABLED=true
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
      - LOGGING_LEVEL_ES_MINDDATA_CHALLENGE=DEBUG
    depends_on:
      - redis

  redis:
    image: redis:latest
    ports:
      - "6379:6379"